from _typeshed import Incomplete
from collections.abc import Generator
from whoosh.compat import abstractmethod as abstractmethod
from whoosh.filedb.filestore import OverlayStorage as OverlayStorage
from whoosh.matching import MultiMatcher as MultiMatcher
from whoosh.support.levenshtein import distance as distance
from whoosh.system import emptybytes as emptybytes

class ReaderClosed(Exception):
    message: str

class TermNotFound(Exception): ...

class TermInfo:
    def __init__(
        self,
        weight: int = 0,
        df: int = 0,
        minlength=None,
        maxlength: int = 0,
        maxweight: int = 0,
        minid=None,
        maxid: int = 0,
    ) -> None: ...
    def add_posting(self, docnum, weight, length=None) -> None: ...
    def weight(self): ...
    def doc_frequency(self): ...
    def min_length(self): ...
    def max_length(self): ...
    def max_weight(self): ...
    def min_id(self): ...
    def max_id(self): ...

class IndexReader:
    def __enter__(self): ...
    def __exit__(self, *args) -> None: ...
    @abstractmethod
    def __contains__(self, term) -> bool: ...
    def codec(self) -> None: ...
    def segment(self) -> None: ...
    def storage(self) -> None: ...
    def is_atomic(self): ...
    def close(self) -> None: ...
    def generation(self) -> None: ...
    @abstractmethod
    def indexed_field_names(self) -> None: ...
    @abstractmethod
    def all_terms(self) -> None: ...
    def terms_from(self, fieldname, prefix) -> Generator[Incomplete]: ...
    @abstractmethod
    def term_info(self, fieldname, text) -> None: ...
    def expand_prefix(self, fieldname, prefix) -> Generator[Incomplete]: ...
    def lexicon(self, fieldname) -> Generator[Incomplete]: ...
    def field_terms(self, fieldname) -> Generator[Incomplete]: ...
    def __iter__(self): ...
    def iter_from(self, fieldname, text) -> Generator[Incomplete]: ...
    def iter_field(self, fieldname, prefix: str = "") -> Generator[Incomplete]: ...
    def iter_prefix(self, fieldname, prefix) -> Generator[Incomplete]: ...
    @abstractmethod
    def has_deletions(self) -> None: ...
    def all_doc_ids(self): ...
    def iter_docs(self) -> Generator[Incomplete]: ...
    @abstractmethod
    def is_deleted(self, docnum) -> None: ...
    @abstractmethod
    def stored_fields(self, docnum) -> None: ...
    def all_stored_fields(self) -> Generator[Incomplete]: ...
    @abstractmethod
    def doc_count_all(self) -> None: ...
    @abstractmethod
    def doc_count(self): ...
    @abstractmethod
    def frequency(self, fieldname, text) -> None: ...
    @abstractmethod
    def doc_frequency(self, fieldname, text) -> None: ...
    @abstractmethod
    def field_length(self, fieldname) -> None: ...
    @abstractmethod
    def min_field_length(self, fieldname) -> None: ...
    @abstractmethod
    def max_field_length(self, fieldname) -> None: ...
    @abstractmethod
    def doc_field_length(self, docnum, fieldname, default: int = 0) -> None: ...
    def first_id(self, fieldname, text): ...
    def iter_postings(self) -> Generator[Incomplete]: ...
    @abstractmethod
    def postings(self, fieldname, text) -> None: ...
    @abstractmethod
    def has_vector(self, docnum, fieldname) -> None: ...
    @abstractmethod
    def vector(self, docnum, fieldname, format_=None) -> None: ...
    def vector_as(self, astype, docnum, fieldname) -> Generator[Incomplete]: ...
    def corrector(self, fieldname): ...
    def terms_within(self, fieldname, text, maxdist, prefix: int = 0) -> Generator[Incomplete]: ...
    def most_frequent_terms(self, fieldname, number: int = 5, prefix: str = ""): ...
    def most_distinctive_terms(self, fieldname, number: int = 5, prefix: str = ""): ...
    def leaf_readers(self): ...
    def supports_caches(self): ...
    def has_column(self, fieldname): ...
    def column_reader(self, fieldname, column=None, reverse: bool = False, translate: bool = False) -> None: ...

class SegmentReader(IndexReader):
    schema: Incomplete
    is_closed: bool
    def __init__(self, storage, schema, segment, generation=None, codec=None) -> None: ...
    def codec(self): ...
    def segment(self): ...
    def storage(self): ...
    def has_deletions(self): ...
    def doc_count(self): ...
    def doc_count_all(self): ...
    def is_deleted(self, docnum): ...
    def generation(self): ...
    def __contains__(self, term) -> bool: ...
    def close(self) -> None: ...
    def stored_fields(self, docnum): ...
    def all_doc_ids(self): ...
    def iter_docs(self): ...
    def all_stored_fields(self): ...
    def field_length(self, fieldname): ...
    def min_field_length(self, fieldname): ...
    def max_field_length(self, fieldname): ...
    def doc_field_length(self, docnum, fieldname, default: int = 0): ...
    def has_vector(self, docnum, fieldname): ...
    def indexed_field_names(self): ...
    def all_terms(self): ...
    def terms_from(self, fieldname, prefix): ...
    def term_info(self, fieldname, text): ...
    def expand_prefix(self, fieldname, prefix): ...
    def lexicon(self, fieldname): ...
    def __iter__(self): ...
    def iter_from(self, fieldname, text) -> Generator[Incomplete]: ...
    def frequency(self, fieldname, text): ...
    def doc_frequency(self, fieldname, text): ...
    def postings(self, fieldname, text, scorer=None): ...
    def vector(self, docnum, fieldname, format_=None): ...
    def cursor(self, fieldname): ...
    def terms_within(self, fieldname, text, maxdist, prefix: int = 0): ...
    def has_column(self, fieldname): ...
    def column_reader(self, fieldname, column=None, reverse: bool = False, translate: bool = True): ...

class EmptyReader(IndexReader):
    schema: Incomplete
    def __init__(self, schema) -> None: ...
    def __contains__(self, term) -> bool: ...
    def __iter__(self): ...
    def cursor(self, fieldname): ...
    def indexed_field_names(self): ...
    def all_terms(self): ...
    def term_info(self, fieldname, text) -> None: ...
    def iter_from(self, fieldname, text): ...
    def iter_field(self, fieldname, prefix: str = ""): ...
    def iter_prefix(self, fieldname, prefix: str = ""): ...
    def lexicon(self, fieldname): ...
    def has_deletions(self): ...
    def is_deleted(self, docnum): ...
    def stored_fields(self, docnum) -> None: ...
    def all_stored_fields(self): ...
    def doc_count_all(self): ...
    def doc_count(self): ...
    def frequency(self, fieldname, text): ...
    def doc_frequency(self, fieldname, text): ...
    def field_length(self, fieldname): ...
    def min_field_length(self, fieldname): ...
    def max_field_length(self, fieldname): ...
    def doc_field_length(self, docnum, fieldname, default: int = 0): ...
    def postings(self, fieldname, text, scorer=None) -> None: ...
    def has_vector(self, docnum, fieldname): ...
    def vector(self, docnum, fieldname, format_=None) -> None: ...
    def most_frequent_terms(self, fieldname, number: int = 5, prefix: str = ""): ...
    def most_distinctive_terms(self, fieldname, number: int = 5, prefix=None): ...

class MultiReader(IndexReader):
    readers: Incomplete
    schema: Incomplete
    doc_offsets: Incomplete
    base: int
    is_closed: bool
    def __init__(self, readers, generation=None) -> None: ...
    def cursor(self, fieldname): ...
    def is_atomic(self): ...
    def leaf_readers(self): ...
    def add_reader(self, reader) -> None: ...
    def close(self) -> None: ...
    def generation(self): ...
    def format(self, fieldname): ...
    def vector_format(self, fieldname): ...
    def __contains__(self, term) -> bool: ...
    def indexed_field_names(self): ...
    def all_terms(self): ...
    def terms_from(self, fieldname, prefix): ...
    def term_info(self, fieldname, text): ...
    def frequency(self, fieldname, text): ...
    def doc_frequency(self, fieldname, text): ...
    def postings(self, fieldname, text): ...
    def first_id(self, fieldname, text): ...
    def has_deletions(self): ...
    def is_deleted(self, docnum): ...
    def stored_fields(self, docnum): ...
    def has_column(self, fieldname): ...
    def column_reader(self, fieldname, column=None, reverse: bool = False, translate: bool = True): ...
    def all_stored_fields(self) -> Generator[Incomplete]: ...
    def doc_count_all(self): ...
    def doc_count(self): ...
    def field_length(self, fieldname): ...
    def min_field_length(self, fieldname): ...
    def max_field_length(self, fieldname): ...
    def doc_field_length(self, docnum, fieldname, default: int = 0): ...
    def has_vector(self, docnum, fieldname): ...
    def vector(self, docnum, fieldname, format_=None): ...
    def vector_as(self, astype, docnum, fieldname): ...

def combine_terminfos(tis): ...

class MultiCursor:
    def __init__(self, cursors) -> None: ...
    def first(self): ...
    def find(self, term): ...
    def next(self): ...
    def term_info(self): ...
    def is_valid(self): ...
