from _typeshed import Incomplete
from collections.abc import Generator

class NoTermsException(Exception):
    message: str

class TimeLimit(Exception): ...

class SearchContext:
    needs_current: Incomplete
    weighting: Incomplete
    top_query: Incomplete
    limit: Incomplete
    def __init__(self, needs_current: bool = False, weighting=None, top_query=None, limit: int = 0) -> None: ...
    def set(self, **kwargs): ...

class Searcher:
    ixreader: Incomplete
    is_closed: bool
    parent: Incomplete
    schema: Incomplete
    weighting: Incomplete
    leafreaders: Incomplete
    subsearchers: Incomplete
    def __init__(self, reader, weighting=..., closereader: bool = True, fromindex=None, parent=None) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc_info) -> None: ...
    def leaf_searchers(self): ...
    def is_atomic(self): ...
    def has_parent(self): ...
    def get_parent(self) -> Searcher | None: ...
    def doc_count(self): ...
    def doc_count_all(self): ...
    def field_length(self, fieldname): ...
    def max_field_length(self, fieldname): ...
    def up_to_date(self): ...
    def refresh(self): ...
    def close(self) -> None: ...
    def avg_field_length(self, fieldname, default=None): ...
    def reader(self): ...
    def context(self, **kwargs): ...
    def boolean_context(self): ...
    def postings(self, fieldname, text, weighting=None, qf: int = 1): ...
    def idf(self, fieldname, text): ...
    def document(self, **kw): ...
    def documents(self, **kw): ...
    def document_number(self, **kw): ...
    def document_numbers(self, **kw): ...
    def suggest(self, fieldname, text, limit: int = 5, maxdist: int = 2, prefix: int = 0): ...
    def key_terms(self, docnums, fieldname, numterms: int = 5, model=..., normalize: bool = True): ...
    def key_terms_from_text(self, fieldname, text, numterms: int = 5, model=..., normalize: bool = True): ...
    def more_like(
        self,
        docnum,
        fieldname,
        text=None,
        top: int = 10,
        numterms: int = 5,
        model=...,
        normalize: bool = False,
        filter=None,
    ): ...
    def search_page(self, query, pagenum, pagelen: int = 10, **kwargs): ...
    def find(self, defaultfield, querystring, **kwargs): ...
    def docs_for_query(self, q, for_deletion: bool = False) -> Generator[Incomplete]: ...
    def collector(
        self,
        limit: int = 10,
        sortedby=None,
        reverse: bool = False,
        groupedby=None,
        collapse=None,
        collapse_limit: int = 1,
        collapse_order=None,
        optimize: bool = True,
        filter=None,
        mask=None,
        terms: bool = False,
        maptype=None,
        scored: bool = True,
    ): ...
    def search(self, q, **kwargs): ...
    def search_with_collector(self, q, collector, context=None) -> None: ...
    def correct_query(
        self, q, qstring, correctors=None, terms=None, maxdist: int = 2, prefix: int = 0, aliases=None
    ): ...

class Results:
    searcher: Incomplete
    q: Incomplete
    top_n: Incomplete
    docset: Incomplete
    runtime: Incomplete
    highlighter: Incomplete
    collector: Incomplete
    def __init__(self, searcher, q, top_n, docset=None, facetmaps=None, runtime: int = 0, highlighter=None) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, n): ...
    def __iter__(self): ...
    def __contains__(self, docnum) -> bool: ...
    def __nonzero__(self): ...
    __bool__ = __nonzero__
    def is_empty(self): ...
    def items(self): ...
    def fields(self, n): ...
    def facet_names(self): ...
    def groups(self, name=None): ...
    def has_exact_length(self): ...
    def estimated_length(self): ...
    def estimated_min_length(self): ...
    def scored_length(self): ...
    def docs(self): ...
    def copy(self): ...
    def score(self, n): ...
    def docnum(self, n): ...
    def query_terms(self, expand: bool = False, fieldname=None): ...
    def has_matched_terms(self): ...
    def matched_terms(self): ...
    fragmenter: Incomplete
    formatter: Incomplete
    scorer: Incomplete
    order: Incomplete
    def key_terms(self, fieldname, docs: int = 10, numterms: int = 5, model=..., normalize: bool = True): ...
    def extend(self, results) -> None: ...
    def filter(self, results) -> None: ...
    def upgrade(self, results, reverse: bool = False) -> None: ...
    def upgrade_and_extend(self, results) -> None: ...

class Hit:
    results: Incomplete
    searcher: Incomplete
    reader: Incomplete
    pos: Incomplete
    docnum: Incomplete
    score: Incomplete
    def __init__(self, results, docnum, pos=None, score=None) -> None: ...
    def fields(self): ...
    def matched_terms(self): ...
    def highlights(self, fieldname, text=None, top: int = 3, minscore: int = 1): ...
    def more_like_this(
        self, fieldname, text=None, top: int = 10, numterms: int = 5, model=..., normalize: bool = True, filter=None
    ): ...
    def __eq__(self, other): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __getitem__(self, fieldname): ...
    def __contains__(self, key) -> bool: ...
    def items(self): ...
    def keys(self): ...
    def values(self): ...
    def iteritems(self): ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def get(self, key, default=None): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key, value) -> None: ...
    def clear(self) -> None: ...
    def update(self, dict=None, **kwargs) -> None: ...

class ResultsPage:
    results: Incomplete
    total: Incomplete
    pagecount: Incomplete
    pagenum: Incomplete
    offset: Incomplete
    pagelen: Incomplete
    def __init__(self, results, pagenum, pagelen: int = 10) -> None: ...
    def __getitem__(self, n): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def scored_length(self): ...
    def score(self, n): ...
    def docnum(self, n): ...
    def is_last_page(self): ...
