from _typeshed import Incomplete
from collections.abc import Generator
from whoosh.analysis import Token as Token
from whoosh.qparser.compound import CompoundQuery
from whoosh.qcore import Query

class Sequence(CompoundQuery):
    JOINT: str
    intersect_merge: bool
    slop: Incomplete
    ordered: Incomplete
    def __init__(self, subqueries, slop: int = 1, ordered: bool = True, boost: float = 1.0) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def normalize(self): ...
    def estimate_size(self, ixreader): ...
    def estimate_min_size(self, ixreader): ...

class Ordered(Sequence):
    JOINT: str

class Phrase(Query):
    fieldname: Incomplete
    words: Incomplete
    slop: Incomplete
    boost: Incomplete
    char_ranges: Incomplete
    def __init__(self, fieldname, words, slop: int = 1, boost: float = 1.0, char_ranges=None) -> None: ...
    def __eq__(self, other): ...
    def __unicode__(self): ...
    def __hash__(self): ...
    def has_terms(self): ...
    def terms(self, phrases: bool = False) -> Generator[Incomplete]: ...
    def tokens(self, boost: float = 1.0) -> Generator[Incomplete]: ...
    def normalize(self): ...
    def replace(self, fieldname, oldtext, newtext): ...
    def estimate_size(self, ixreader): ...
    def estimate_min_size(self, ixreader): ...
    def matcher(self, searcher, context=None): ...
