from _typeshed import Incomplete
from collections.abc import Generator
from whoosh.matching import ConstantScoreMatcher
from whoosh.query import Query

class ColumnQuery(Query):
    fieldname: Incomplete
    condition: Incomplete
    def __init__(self, fieldname, condition) -> None: ...
    def is_leaf(self): ...
    def matcher(self, searcher, context=None): ...

class ColumnMatcher(ConstantScoreMatcher):
    creader: Incomplete
    condition: Incomplete
    def __init__(self, creader, condition) -> None: ...
    def is_active(self): ...
    def next(self) -> None: ...
    def reset(self) -> None: ...
    def id(self): ...
    def all_ids(self) -> Generator[Incomplete]: ...
    def supports(self, astype): ...
    def skip_to_quality(self, minquality): ...
