from _typeshed import Incomplete

class QueryParserError(Exception):
    cause: Incomplete
    def __init__(self, cause, msg=None) -> None: ...

def get_single_text(field, text, **kwargs): ...
def attach(q, stxnode): ...
def print_debug(level, msg, out=...) -> None: ...
