from _typeshed import Incomplete
from whoosh.qparser.taggers import FnTagger as FnTagger, RegexTagger as RegexTagger
from whoosh.qparser.syntax import GroupNode, MarkerNode, SyntaxNode, TextNode, Whitespace, WordNode

class Plugin:
    def taggers(self, parser): ...
    def filters(self, parser): ...

class TaggingPlugin(RegexTagger):
    priority: int
    expr: Incomplete
    def __init__(self, expr=None) -> None: ...
    def taggers(self, parser): ...
    def filters(self, parser): ...
    def create(self, parser, match): ...

class WhitespacePlugin(TaggingPlugin):
    nodetype = Whitespace
    priority: int
    def __init__(self, expr: str = "\\s+") -> None: ...
    def filters(self, parser): ...
    def remove_whitespace(self, parser, group): ...

class SingleQuotePlugin(TaggingPlugin):
    expr: str
    nodetype = WordNode

class PrefixPlugin(TaggingPlugin):
    class PrefixNode(TextNode):
        qclass: Incomplete
        def r(self): ...

    expr: str
    nodetype = PrefixNode

class WildcardPlugin(TaggingPlugin):
    qmarks: Incomplete
    expr: Incomplete
    def filters(self, parser): ...
    def do_wildcards(self, parser, group): ...

    class WildcardNode(TextNode):
        qclass: Incomplete
        def r(self): ...

    nodetype = WildcardNode

class RegexPlugin(TaggingPlugin):
    class RegexNode(TextNode):
        qclass: Incomplete
        def r(self): ...

    expr: str
    nodetype = RegexNode

class BoostPlugin(TaggingPlugin):
    expr: str

    class BoostNode(SyntaxNode):
        original: Incomplete
        boost: Incomplete
        def __init__(self, original, boost) -> None: ...
        def r(self): ...

    def create(self, parser, match): ...
    def filters(self, parser): ...
    def clean_boost(self, parser, group): ...
    def do_boost(self, parser, group): ...

class GroupPlugin(Plugin):
    class OpenBracket(SyntaxNode):
        def r(self): ...

    class CloseBracket(SyntaxNode):
        def r(self): ...

    openexpr: Incomplete
    closeexpr: Incomplete
    def __init__(self, openexpr: str = "[(]", closeexpr: str = "[)]") -> None: ...
    def taggers(self, parser): ...
    def filters(self, parser): ...
    def do_groups(self, parser, group): ...

class EveryPlugin(TaggingPlugin):
    expr: str
    priority: int
    def create(self, parser, match): ...

    class EveryNode(SyntaxNode):
        def r(self): ...
        def query(self, parser): ...

class FieldsPlugin(TaggingPlugin):
    class FieldnameTagger(RegexTagger):
        def create(self, parser, match): ...

    expr: Incomplete
    removeunknown: Incomplete
    def __init__(self, expr: str = "(?P<text>\\w+|[*]):", remove_unknown: bool = True) -> None: ...
    def taggers(self, parser): ...
    def filters(self, parser): ...
    def do_fieldnames(self, parser, group): ...

class FuzzyTermPlugin(TaggingPlugin):
    expr: Incomplete

    class FuzzinessNode(SyntaxNode):
        maxdist: Incomplete
        prefixlength: Incomplete
        original: Incomplete
        def __init__(self, maxdist, prefixlength, original) -> None: ...

    class FuzzyTermNode(TextNode):
        qclass: Incomplete
        fieldname: Incomplete
        text: Incomplete
        boost: Incomplete
        startchar: Incomplete
        endchar: Incomplete
        maxdist: Incomplete
        prefixlength: Incomplete
        def __init__(self, wordnode, maxdist, prefixlength) -> None: ...
        def r(self): ...
        def query(self, parser): ...

    def create(self, parser, match): ...
    def filters(self, parser): ...
    def do_fuzzyterms(self, parser, group): ...

class FunctionPlugin(TaggingPlugin):
    expr: Incomplete

    class FunctionNode(SyntaxNode):
        has_fieldname: bool
        has_boost: bool
        merging: bool
        name: Incomplete
        fn: Incomplete
        args: Incomplete
        kwargs: Incomplete
        nodes: Incomplete
        boost: Incomplete
        def __init__(self, name, fn, args, kwargs) -> None: ...
        def query(self, parser): ...

    fns: Incomplete
    def __init__(self, fns) -> None: ...
    def create(self, parser, match): ...
    def filters(self, parser): ...
    def do_functions(self, parser, group): ...

class PhrasePlugin(Plugin):
    wordexpr: Incomplete

    class PhraseNode(TextNode):
        textstartchar: Incomplete
        slop: Incomplete
        def __init__(self, text, textstartchar, slop: int = 1) -> None: ...
        def r(self): ...
        def apply(self, fn): ...
        def query(self, parser): ...

    class PhraseTagger(RegexTagger):
        def create(self, parser, match): ...

    expr: Incomplete
    def __init__(self, expr: str = '"(?P<text>.*?)"(~(?P<slop>[1-9][0-9]*))?') -> None: ...
    def taggers(self, parser): ...

class SequencePlugin(Plugin):
    expr: Incomplete
    def __init__(self, expr: str = '["](~(?P<slop>[1-9][0-9]*))?') -> None: ...

    class SequenceNode(GroupNode):
        qclass: Incomplete

    class QuoteNode(MarkerNode):
        slop: Incomplete
        def __init__(self, slop=None) -> None: ...

    def taggers(self, parser): ...
    def filters(self, parser): ...
    def do_quotes(self, parser, group): ...

class RangePlugin(Plugin):
    expr: Incomplete

    class RangeTagger(RegexTagger):
        expr: Incomplete
        excl_start: Incomplete
        excl_end: Incomplete
        def __init__(self, expr, excl_start, excl_end) -> None: ...
        def create(self, parser, match): ...

    excl_start: Incomplete
    excl_end: Incomplete
    def __init__(self, expr=None, excl_start: str = "{", excl_end: str = "}") -> None: ...
    def taggers(self, parser): ...

class OperatorsPlugin(Plugin):
    class OpTagger(RegexTagger):
        grouptype: Incomplete
        optype: Incomplete
        leftassoc: Incomplete
        memo: Incomplete
        def __init__(self, expr, grouptype, optype=..., leftassoc: bool = True, memo: str = "") -> None: ...
        def create(self, parser, match): ...

    ops: Incomplete
    def __init__(
        self,
        ops=None,
        clean: bool = False,
        And: str = "(?<=\\s)AND(?=\\s)",
        Or: str = "(?<=\\s)OR(?=\\s)",
        AndNot: str = "(?<=\\s)ANDNOT(?=\\s)",
        AndMaybe: str = "(?<=\\s)ANDMAYBE(?=\\s)",
        Not: str = "(^|(?<=(\\s|[()])))NOT(?=\\s)",
        Require: str = "(^|(?<=\\s))REQUIRE(?=\\s)",
    ) -> None: ...
    def taggers(self, parser): ...
    def filters(self, parser): ...
    def do_operators(self, parser, group): ...

class PlusMinusPlugin(Plugin):
    class Plus(MarkerNode): ...
    class Minus(MarkerNode): ...
    plusexpr: Incomplete
    minusexpr: Incomplete
    def __init__(self, plusexpr: str = "\\+", minusexpr: str = "-") -> None: ...
    def taggers(self, parser): ...
    def filters(self, parser): ...
    def do_plusminus(self, parser, group): ...

class GtLtPlugin(TaggingPlugin):
    class GtLtNode(SyntaxNode):
        rel: Incomplete
        def __init__(self, rel) -> None: ...

    expr: str
    nodetype = GtLtNode
    def filters(self, parser): ...
    def do_gtlt(self, parser, group): ...
    def make_range(self, node, rel): ...

class MultifieldPlugin(Plugin):
    fieldnames: Incomplete
    boosts: Incomplete
    group: Incomplete
    def __init__(self, fieldnames, fieldboosts=None, group=...) -> None: ...
    def filters(self, parser): ...
    def do_multifield(self, parser, group): ...

class FieldAliasPlugin(Plugin):
    fieldmap: Incomplete
    reverse: Incomplete
    def __init__(self, fieldmap) -> None: ...
    def filters(self, parser): ...
    def do_aliases(self, parser, group): ...

class CopyFieldPlugin(Plugin):
    map: Incomplete
    group: Incomplete
    def __init__(self, map, group=..., mirror: bool = False) -> None: ...
    def filters(self, parser): ...
    def do_copyfield(self, parser, group): ...

class PseudoFieldPlugin(Plugin):
    xform_map: Incomplete
    def __init__(self, xform_map) -> None: ...
    def filters(self, parser): ...
    def do_pseudofield(self, parser, group): ...
